# Generated by Django 4.2.7 on 2023-12-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(max_length=255, verbose_name='Role'),
        ),
    ]
